version: "3"
services:
  api_db:
    image: mongo
    volumes:
      - /data/db
  api:
    build: .
    command: yarn run dev
    environment:
      - MONGO_URL=mongodb://api_db:27017
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${EXTERNAL_PORT}:4000
    depends_on:
      - api_db
